### PR TITLE
Enhancements to Pickers and Extension to address JDBC where table names not uppercase

### PR DESCRIPTION
**Pull request by paulswithers**
Extensions to com.ibm.xsp.extlib.relational\src\com\ibm\xsp\extlib\relational\javascript\JdbcFunctions.java and com.ibm.xsp.extlib.relational\src\com\ibm\xsp\extlib\relational\util\JdbcUtil.java to allow users to access columns where the column name is not upper case, both from Java and SSJS

Adding returnNameFormat option for DominoNABNamePickerDataProvider and relevant xsp-config and English localization

Adding MapValuePickerData and CollectionValuePickerData and relevant xsp-config and English localization

Let me know if you want me to send XML for demos of ValuePickers (pwithers@intec.co.uk)

Also adding fix for combo boxes in dialogs with Bootstrap theme (xsp-mixin.css)

namepicker

### CODE REVIEW

**Comment by paulswithers** [comment]
Removed that part of the commit.
I've also added support for searchType option in NamePicker, plus amendment to show everything if searchType="match" and no key is entered (previously it showed nothing)

**Comment by maire-kehoe** [comment]
Since this Pull Request contains many sub-parts in individual commits, for tracking purposes I'm naming the sub-parts as A to D like so:

Part A) "Fix for comboboxes in dialogs with bootstrap theme. Thanks David Leedy and Declan Lynch"

Part B) "Adding Collection and Map picker data providers"

Part C) Adding @JdbcInsertExt and @JdbcUpdateExt
including "Adding JDBC Ext functions and Java code, to avoid capitalisation"
and related "JDBCUtil adding support for not upper-casing column names"

Part D) updates to Domino pickers for returnNameFormat, searchType and initial "match" behavior
covering these 3 semi-related commits:
  Part D1) "DominoNABNamePickerData, starting work on adding returnNameFormat"
     and related "Adding returnNameFormat for NamePicker"
  Part D2) "Adding searchType to NAB picker"
  Part D3) "Amending "match" search option so everything shows if no search value is entered"
     in AbstractDominoViewPickerData 


Part B is included in the 901v00_12 OpenNTF release.
Part A won't be accepted, but the related fix from Brian Gleeson is in the 901v00_12 release (SPR#BGLN9U5JPG).
Part C and D weren't included in release 12 and are being proposed for later releases.

**Comment by maire-kehoe** [comment]
The latest ExtLib OpenNTF release 901v00_14 contains the changes for part D of this pull request. 
The part C commits are still outstanding, but will be considered for a later OpenNTF release.

There were some changes in the delivered code. Notably in the xe:dominoNABNamePicker tag
the new property has been named "valueNameFormat", renamed from the commit's name of "returnNameFormat".
Also, for the change in behavior in D3 there's a new xsp.properties option to revert to the old behavior by setting:
xsp.extlib.dominoViewPicker.searchMatch.emptyKey.all=false

Thanks again for the contributions Paul.

The relevant lines in the Readme.pdf Change Log section are:
- GIT Pull Request 14 (Paul Withers) - Part D1 - DominoNABNamePickerData new valueNameFormat property
- GIT Pull Request 14 (Paul Withers) - Part D2 - Adding searchType to NAB picker
- GIT Pull Request 14 (Paul Withers) - Part D3 - in AbstractDominoViewPickerData, empty search to "match" all
- GIT Pull Request 14 (Paul Withers) - Part D3 - xe:dominoView*Picker, xsp.properties option for search match to return none

**Comment by briangleeson** [comment]
The final part of this pull request (Part C) has been reviewed and merged into the latest ExtLib release (9.0.1 R15). Thanks for you contributions Paul, now closing this PR.

**Pull request closed without merging**
