### PR TITLE
Added an InPlaceFormAction server action and related xsp-config

### PR DESCRIPTION
**Pull request by camac**
It has long annoyed me that there is no simple action for showing and hiding InPlaceForms so I created one!

Basically just copied the ChangeDynamicContentAction and modified as necessary.

Note: I have modified extlib-dynamiccontent.xsp-config to add the complex property config, I understand this is generated somehow but I don't know how to do that so that area might need a look over. I added some properties to the related messages as well.

### CODE REVIEW

**Comment by padraic-edwards** [comment]
Hi Cameron,
Thanks for your contribution, seems handy alright. We will review it and be in touch shortly.

Thanks,
Padraic

**Comment by camac** [comment]
Thanks Padraic!

**Comment by padraic-edwards** [comment]
Hi Cameron,
Thanks very much contributing to the Extension Library. Your contribution has been bluewashed and is now part of the 12th ExtLib release.

Thanks,
Padraic

**Comment by camac** [comment]
Thanks again, I'm very pleased to contribute!

**Pull request closed without merging**
